import type { TemplateSet } from '../types.js'

export const agencyTemplates: TemplateSet[] = [
  {
    id: 'agency-client-persona',
    name: 'Client Persona',
    description: 'An agency client persona with budget, timeline, and decision process: the key details that determine whether a lead becomes a project.',
    industries: ['agency'],
    stages: ['concept', 'validation', 'growth'],
    entities: [
      {
        type: 'persona',
        title_template: '{{client_name}}, {{client_title}} at {{company_type}}',
        description_template: '{{client_motivation}}\n\nGoals: launch {{project_goal}} on time and within budget, find an agency partner who understands the business (not just the deliverable), and demonstrate ROI to internal stakeholders within {{roi_timeline}}.\n\nFrustrations: agencies that over-promise and under-deliver (scope creep, missed deadlines), the difficulty of evaluating agency quality before signing a contract, and communication gaps with no visibility into progress between milestone reviews.',
        default_properties: {
          context: '{{client_context}}. Budget range: {{budget_range}}. Typical project timeline: {{timeline}}. Decision process: {{decision_process}}.',
          is_primary: true,
          audience_role: 'buyer',
        },
        default_tags: ['client', 'agency'],
      },
      {
        type: 'job',
        title_template: 'Find and vet the right agency without wasting months',
        description_template: 'When I need to {{project_goal}}, I want to quickly identify and vet 2-3 qualified agencies, so I can make a confident decision and start the project within {{evaluation_timeline}}.',
        default_properties: {
          statement: 'When I need to {{project_goal}}, I want to quickly identify and vet qualified agencies, so I can start the project within {{evaluation_timeline}}.',
          job_type: 'functional',
          importance: 5,
          current_satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Look smart to my boss by choosing the right partner',
        description_template: 'When I recommend an agency to leadership, I want to show clear criteria, competitive evaluation, and risk mitigation, so I can build credibility and not be blamed if something goes wrong.',
        default_properties: {
          statement: 'When I recommend an agency to leadership, I want to show clear evaluation criteria, so I can build credibility and protect my reputation.',
          job_type: 'social',
          importance: 4,
          current_satisfaction: 2,
        },
      },
      {
        type: 'need',
        title_template: 'Every agency proposal looks the same, impossible to compare',
        description_template: 'RFP responses are full of jargon and case studies but never clearly answer: what will you build, how long, how much, and what happens when scope changes? No standardized way to compare.',
        default_properties: { valence: 'pain', frequency: 4, severity: 4 },
      },
      {
        type: 'need',
        title_template: 'Scope creep turns fixed-bid projects into open-ended money pits',
        description_template: 'What started as a $50K project is now $120K because "requirements evolved." No clear change management process was established upfront, and now neither side is happy.',
        default_properties: { valence: 'pain', frequency: 3, severity: 5 },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1, type: 'persona_pursues_job' },
      { source_index: 0, target_index: 2, type: 'persona_pursues_job' },
      { source_index: 1, target_index: 3, type: 'job_surfaces_need' },
      { source_index: 1, target_index: 4, type: 'job_surfaces_need' },
    ],
    prompts: {
      client_name: "Client persona name?",
      client_title: 'Their title? (e.g. VP of Marketing, Head of Product, Founder)',
      company_type: 'Company type? (e.g. Series B startup, mid-market SaaS, enterprise retail)',
      client_context: 'Describe their world: industry, team size, what pressures they face',
      client_motivation: 'What drives this person to seek agency help?',
      budget_range: 'Typical budget range? (e.g. $20-50K, $50-150K, $200K+)',
      timeline: 'Typical project timeline? (e.g. 6-8 weeks, 3 months, 6 months)',
      decision_process: 'How do they decide? (e.g. solo decision, committee, procurement process)',
      project_goal: 'What do they need done? (e.g. redesign the website, build an MVP, rebrand)',
      roi_timeline: 'When do they need to show ROI? (e.g. 3 months, 6 months, 1 quarter)',
      evaluation_timeline: 'How fast do they need to pick an agency? (e.g. 2 weeks, 1 month)',
    },
  },
  {
    id: 'agency-service-blueprint',
    name: 'Service Blueprint',
    description: 'An agency business model with 3 revenue streams (project-based, retainer, and advisory) covering the full spectrum of how agencies make money.',
    industries: ['agency'],
    stages: ['validation', 'growth'],
    entities: [
      {
        type: 'business_model',
        title_template: '{{agency_name}} Service Blueprint',
        description_template: 'Agency business model for {{agency_name}}. Three revenue streams: project-based delivery, monthly retainers, and strategic advisory. Blended margins target: {{target_margin}}%. Customer segments: {{primary_segment}} and {{secondary_segment}}. Channels: referrals, case studies & content, conference speaking, and LinkedIn thought leadership. Key activities: client delivery, business development, talent management, and methodology development. Key resources: senior practitioners, the delivery methodology, client relationships, and the portfolio & case studies. Key partners: a freelance network, technology partners, and strategic referral partners.',
        default_properties: {
          pattern: 'hybrid',
          status: 'drafted',
        },
        default_tags: ['agency', 'services'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Project-Based Delivery',
        description_template: 'Fixed-scope, fixed-price engagements. Typical size: {{project_size}}. Duration: {{project_duration}}. Margin target: {{project_margin}}%. The bread and butter: predictable delivery, clear milestones.',
        default_properties: { stream_type: 'transaction' },
        default_tags: ['project', 'primary'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Monthly Retainer',
        description_template: 'Ongoing monthly engagements for {{retainer_scope}}. Typical rate: {{retainer_rate}}/month. These provide predictable recurring revenue and deepen client relationships.',
        default_properties: { stream_type: 'subscription' },
        default_tags: ['retainer', 'recurring'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Strategic Advisory',
        description_template: 'High-value, low-effort advisory engagements. {{advisory_hours}} hours/month at {{advisory_rate}}/hour. Senior partners only. Highest margin stream: pure expertise, no delivery overhead.',
        default_properties: { stream_type: 'other' },
        default_tags: ['advisory', 'high-margin'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1, type: 'business_model_earns_via_revenue_stream' },
      { source_index: 0, target_index: 2, type: 'business_model_earns_via_revenue_stream' },
      { source_index: 0, target_index: 3, type: 'business_model_earns_via_revenue_stream' },
    ],
    prompts: {
      agency_name: "What's your agency called?",
      primary_segment: 'Primary client segment? (e.g. Series A-B startups, mid-market SaaS)',
      secondary_segment: 'Secondary segment? (e.g. enterprise innovation teams, funded founders)',
      target_margin: 'Target blended margin? (e.g. 40, 50, 60)',
      project_size: 'Typical project size? (e.g. $30-80K, $50-150K)',
      project_duration: 'Typical project duration? (e.g. 6-8 weeks, 3 months)',
      project_margin: 'Project margin target? (e.g. 35, 45)',
      retainer_scope: 'What do retainers cover? (e.g. ongoing design support, growth marketing, fractional CTO)',
      retainer_rate: 'Typical retainer rate? (e.g. $5K, $10K, $15K)',
      advisory_hours: 'Advisory hours/month? (e.g. 4, 8, 10)',
      advisory_rate: 'Advisory hourly rate? (e.g. $300, $500)',
    },
  },
  {
    id: 'agency-engagement-kickoff',
    name: 'Engagement Kickoff',
    description: 'A release milestone with the 5 phases of a client engagement: discovery, strategy, execution, review, and handoff. The operational backbone of every project.',
    industries: ['agency'],
    stages: ['validation', 'growth', 'mature'],
    entities: [
      {
        type: 'release',
        title_template: '{{project_name}}: {{client_name}} Engagement',
        description_template: 'Full engagement for {{client_name}}. Scope: {{engagement_scope}}. Timeline: {{engagement_timeline}}. Budget: {{engagement_budget}}.',
        default_properties: {},
        default_tags: ['engagement', 'client-project'],
      },
      {
        type: 'feature',
        title_template: 'Phase 1: Discovery & Requirements',
        description_template: 'Stakeholder interviews, requirements gathering, technical audit, and scope definition. Deliverable: detailed project brief and success criteria. Duration: {{discovery_duration}}.',
        default_properties: { status: 'proposed' },
        default_tags: ['discovery', 'phase-1'],
      },
      {
        type: 'feature',
        title_template: 'Phase 2: Strategy & Architecture',
        description_template: 'Solution design, technology selection, information architecture, and project plan. Deliverable: strategy deck, technical architecture doc, and sprint plan. Duration: {{strategy_duration}}.',
        default_properties: { status: 'proposed' },
        default_tags: ['strategy', 'phase-2'],
      },
      {
        type: 'feature',
        title_template: 'Phase 3: Execution & Build',
        description_template: 'Design, development, and iterative delivery in {{sprint_cadence}} sprints. Client reviews at each milestone. Deliverable: working product increments. Duration: {{execution_duration}}.',
        default_properties: { status: 'proposed' },
        default_tags: ['execution', 'phase-3'],
      },
      {
        type: 'feature',
        title_template: 'Phase 4: QA & Client Review',
        description_template: 'End-to-end testing, accessibility audit, performance testing, and client UAT. Deliverable: signed-off release candidate with known issues documented. Duration: {{review_duration}}.',
        default_properties: { status: 'proposed' },
        default_tags: ['qa', 'phase-4'],
      },
      {
        type: 'feature',
        title_template: 'Phase 5: Launch & Handoff',
        description_template: 'Production deployment, documentation handoff, team training, and 30-day hypercare support. Deliverable: live product, runbooks, and knowledge transfer sessions. Duration: {{handoff_duration}}.',
        default_properties: { status: 'proposed' },
        default_tags: ['launch', 'handoff', 'phase-5'],
      },
    ],
    edges: [],
    prompts: {
      project_name: 'Project name? (e.g. Website Redesign, MVP Build, Brand Refresh)',
      client_name: 'Client name or company?',
      engagement_scope: 'High-level scope? (e.g. redesign marketing site, build mobile MVP, product strategy)',
      engagement_timeline: 'Total timeline? (e.g. 10 weeks, 3 months, 6 months)',
      engagement_budget: 'Budget? (e.g. $60K, $120K, TBD)',
      discovery_duration: 'Discovery phase duration? (e.g. 1 week, 2 weeks)',
      strategy_duration: 'Strategy phase duration? (e.g. 1 week, 2 weeks)',
      sprint_cadence: 'Sprint cadence? (e.g. 1-week, 2-week)',
      execution_duration: 'Execution phase duration? (e.g. 4 weeks, 6 weeks, 8 weeks)',
      review_duration: 'QA/review duration? (e.g. 1 week, 2 weeks)',
      handoff_duration: 'Handoff + hypercare duration? (e.g. 1 week + 30 days support)',
    },
  },
]
