import type { TemplateSet } from '../types.js'

export const marketplaceTemplates: TemplateSet[] = [
  {
    id: 'marketplace-two-sided-personas',
    name: 'Two-Sided Persona Pair',
    description: 'A buyer persona and a seller persona, each with 2 jobs-to-be-done: the foundation for any marketplace where both sides need to win.',
    industries: ['marketplace'],
    stages: ['idea', 'mvp'],
    entities: [
      {
        type: 'persona',
        title_template: '{{buyer_name}}, {{buyer_role}}',
        description_template: '{{buyer_motivation}}',
        default_properties: {
          context: '{{buyer_context}}',
          goals: ['Find the right {{supply_noun}} quickly without wading through noise', 'Get reliable quality and transparent pricing'],
          frustrations: ['Too many low-quality options to sift through', 'No way to verify quality before committing'],
        },
        default_tags: ['buyer', 'demand-side'],
      },
      {
        type: 'job',
        title_template: 'Find and evaluate {{supply_noun}} I can trust',
        description_template: 'When I need a {{supply_noun}}, I want to quickly compare options with verified reviews and transparent pricing, so I can make a confident decision without wasting time.',
        default_properties: {
          statement: 'When I need a {{supply_noun}}, I want to quickly compare options with verified reviews and transparent pricing, so I can make a confident decision without wasting time.',
          job_type: 'functional',
          importance: 5,
          satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Get ongoing value after the first transaction',
        description_template: 'When I have found a good {{supply_noun}}, I want to build an ongoing relationship and get better deals over time, so I can stop searching and start benefiting.',
        default_properties: {
          statement: 'When I have found a good {{supply_noun}}, I want to build an ongoing relationship, so I can stop searching and start benefiting.',
          job_type: 'emotional',
          importance: 3,
          satisfaction: 2,
        },
      },
      {
        type: 'persona',
        title_template: '{{seller_name}}, {{seller_role}}',
        description_template: '{{seller_motivation}}',
        default_properties: {
          context: '{{seller_context}}',
          goals: ['Reach more {{demand_noun}} without spending on ads', 'Build a reputation that compounds over time'],
          frustrations: ['Competing on price alone, no way to stand out on quality', 'Platform takes too large a cut for the value it provides'],
        },
        default_tags: ['seller', 'supply-side'],
      },
      {
        type: 'job',
        title_template: 'Get discovered by {{demand_noun}} who value quality',
        description_template: 'When I have a great {{supply_noun}} to offer, I want to be found by {{demand_noun}} who care about quality over price, so I can build a sustainable business without racing to the bottom.',
        default_properties: {
          statement: 'When I have a great {{supply_noun}} to offer, I want to be found by {{demand_noun}} who care about quality, so I can build a sustainable business.',
          job_type: 'functional',
          importance: 5,
          satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Manage bookings and payments without admin overhead',
        description_template: 'When I get a new {{demand_noun}}, I want the booking, payment, and communication to be handled seamlessly, so I can focus on delivering great work instead of chasing invoices.',
        default_properties: {
          statement: 'When I get a new {{demand_noun}}, I want bookings and payments handled seamlessly, so I can focus on delivering great work.',
          job_type: 'functional',
          importance: 4,
          satisfaction: 3,
        },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 3, target_index: 4 },
      { source_index: 3, target_index: 5 },
    ],
    prompts: {
      buyer_name: "Buyer persona name? (e.g. Maya, Alex)",
      buyer_role: 'Buyer role? (e.g. Homeowner, Small Business Owner, Hiring Manager)',
      buyer_context: "Describe the buyer's world: who are they, what do they need?",
      buyer_motivation: 'What drives the buyer? Why are they searching?',
      seller_name: 'Seller persona name?',
      seller_role: 'Seller role? (e.g. Freelance Designer, Local Contractor, Course Creator)',
      seller_context: "Describe the seller's world: what do they offer, how do they work?",
      seller_motivation: "What drives the seller? Why do they want a platform?",
      supply_noun: 'What does the seller provide? (e.g. design service, cleaning service, online course)',
      demand_noun: 'What do you call the buyers? (e.g. clients, customers, students)',
    },
  },
  {
    id: 'marketplace-business-model',
    name: 'Marketplace Business Model',
    description: 'A marketplace business model with take-rate and subscription revenue streams, plus value propositions for both sides of the market.',
    industries: ['marketplace'],
    stages: ['mvp', 'growth'],
    entities: [
      {
        type: 'business_model',
        title_template: '{{marketplace_name}} Marketplace Model',
        description_template: 'Two-sided marketplace connecting {{supply_side}} with {{demand_side}}. Monetises through transaction fees and optional premium subscriptions.',
        default_properties: {
          canvas_type: 'lean',
          customer_segments: ['{{supply_side}}', '{{demand_side}}'],
          channels: ['Organic search', 'Word of mouth', 'Social proof / reviews'],
          key_activities: ['Supply acquisition', 'Demand generation', 'Trust & safety', 'Matching quality'],
          key_resources: ['Platform technology', 'Review/rating system', 'Customer support'],
          status: 'draft',
        },
        default_tags: ['marketplace', 'two-sided'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Take Rate: {{take_rate}}% per transaction',
        description_template: 'Commission on each completed transaction. {{take_rate}}% of GMV. This is the primary revenue driver; scales directly with marketplace activity.',
        default_properties: {},
        default_tags: ['take-rate', 'primary'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Premium Subscription for {{supply_side}}',
        description_template: 'Optional subscription for {{supply_side}} who want priority placement, analytics, and reduced take rate. Target: {{subscription_price}}/month.',
        default_properties: {},
        default_tags: ['subscription', 'supply-side'],
      },
      {
        type: 'value_proposition',
        title_template: 'For {{demand_side}}: Trusted {{supply_noun}} without the search cost',
        description_template: 'For {{demand_side}} tired of unreliable options, {{marketplace_name}} provides vetted {{supply_noun}} with verified reviews, transparent pricing, and guaranteed quality.',
        default_properties: {
          for_segment: '{{demand_side}}',
          gains: ['Save time finding quality {{supply_noun}}', 'Confidence through verified reviews', 'Price transparency'],
          pain_relievers: ['No more vetting unreliable options', 'Dispute resolution if things go wrong'],
          status: 'draft',
        },
      },
      {
        type: 'value_proposition',
        title_template: 'For {{supply_side}}: Steady demand without marketing spend',
        description_template: 'For {{supply_side}} struggling to find customers, {{marketplace_name}} delivers qualified {{demand_side}} directly: no ads, no cold outreach, just great work that compounds into reputation.',
        default_properties: {
          for_segment: '{{supply_side}}',
          gains: ['Steady stream of qualified leads', 'Reputation that compounds over time', 'Handled payments and admin'],
          pain_relievers: ['No marketing spend required', 'No invoice chasing'],
          status: 'draft',
        },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 0, target_index: 3 },
      { source_index: 0, target_index: 4 },
    ],
    prompts: {
      marketplace_name: "What's your marketplace called?",
      supply_side: 'Who are the sellers/providers? (e.g. freelance designers, local cleaners, tutors)',
      demand_side: 'Who are the buyers/customers? (e.g. startups, homeowners, students)',
      supply_noun: 'What is being sold/provided? (e.g. design work, cleaning services, lessons)',
      take_rate: 'What transaction fee %? (e.g. 10, 15, 20)',
      subscription_price: 'Premium subscription price? (e.g. $29, $99)',
    },
  },
  {
    id: 'marketplace-hypothesis-set',
    name: 'Supply-Demand Hypothesis Set',
    description: '3 hypotheses testing the chicken-and-egg problem: can you attract supply, generate demand, and match them effectively?',
    industries: ['marketplace'],
    stages: ['idea', 'mvp'],
    entities: [
      {
        type: 'hypothesis',
        title_template: 'Supply: {{supply_side}} will list on {{marketplace_name}} without upfront payment',
        description_template: 'We believe {{supply_side}} will create profiles and list their offerings for free because the promise of qualified leads outweighs the setup effort.',
        default_properties: {
          we_believe: '{{supply_side}} will onboard without upfront payment',
          will_result_in: '{{supply_target}} active listings within {{supply_timeline}}',
          we_know_when: 'We have {{supply_target}} listings with complete profiles',
          status: 'untested',
        },
        default_tags: ['supply-hypothesis', 'chicken-egg'],
      },
      {
        type: 'hypothesis',
        title_template: 'Demand: {{demand_side}} will choose {{marketplace_name}} over {{current_alternative}}',
        description_template: 'We believe {{demand_side}} currently using {{current_alternative}} will switch to {{marketplace_name}} because of better {{key_advantage}}.',
        default_properties: {
          we_believe: '{{demand_side}} will switch from {{current_alternative}}',
          will_result_in: '{{demand_target}} completed transactions within {{demand_timeline}}',
          we_know_when: 'Transaction count exceeds {{demand_target}} with >{{repeat_rate}}% repeat rate',
          status: 'untested',
        },
        default_tags: ['demand-hypothesis', 'chicken-egg'],
      },
      {
        type: 'hypothesis',
        title_template: 'Matching: Algorithmic matching outperforms manual search',
        description_template: 'We believe automated matching based on {{matching_criteria}} will produce better outcomes than users browsing and filtering manually.',
        default_properties: {
          we_believe: 'Algorithmic matching outperforms manual search',
          will_result_in: 'Higher satisfaction scores and faster time-to-match',
          we_know_when: 'Matched users rate satisfaction >{{satisfaction_target}}/5 and complete transactions {{speed_improvement}} faster',
          status: 'untested',
        },
        default_tags: ['matching-hypothesis'],
      },
    ],
    edges: [],
    prompts: {
      marketplace_name: "What's your marketplace called?",
      supply_side: 'Who provides supply? (e.g. freelancers, hosts, tutors)',
      demand_side: 'Who creates demand? (e.g. businesses, travelers, students)',
      current_alternative: 'What do demand-side users do today? (e.g. Google search, word of mouth, Craigslist)',
      key_advantage: 'What advantage do you offer over that alternative? (e.g. trust/reviews, speed, curation)',
      supply_target: 'How many supply listings validates the hypothesis? (e.g. 50, 200)',
      supply_timeline: 'In what timeframe? (e.g. 30 days, 3 months)',
      demand_target: 'How many transactions validates demand? (e.g. 100, 500)',
      demand_timeline: 'In what timeframe?',
      repeat_rate: 'What repeat purchase rate? (e.g. 20, 40)',
      matching_criteria: 'What signals would matching use? (e.g. location + skills + availability, preferences + budget + reviews)',
      satisfaction_target: 'Target satisfaction score out of 5? (e.g. 4, 4.5)',
      speed_improvement: 'How much faster? (e.g. 2x, 50%)',
    },
  },
]
