import type { TemplateSet } from '../types.js'

export const mobileTemplates: TemplateSet[] = [
  {
    id: 'mobile-user-persona',
    name: 'Mobile User Persona',
    description: 'A mobile-first user persona with 2 jobs-to-be-done and pain points focused on on-the-go context, interruptions, and small-screen constraints.',
    industries: ['mobile'],
    stages: ['idea', 'mvp'],
    entities: [
      {
        type: 'persona',
        title_template: '{{persona_name}}, {{persona_role}}',
        description_template: '{{persona_motivation}}',
        default_properties: {
          context: '{{persona_context}}. Uses their phone {{phone_usage}} per day. Primary device: {{primary_device}}.',
          goals: ['Get things done in micro-moments between other activities', 'Have a seamless experience that works on spotty connections'],
          frustrations: ['Apps that require too many taps for simple actions', 'Features that only work well on desktop: mobile feels like an afterthought'],
        },
        default_tags: ['mobile-user', 'on-the-go'],
      },
      {
        type: 'job',
        title_template: 'Capture {{capture_what}} before I forget',
        description_template: 'When I have a quick moment between tasks, I want to capture {{capture_what}} in under 10 seconds, so I can get back to what I was doing without losing the thought.',
        default_properties: {
          statement: 'When I have a quick moment between tasks, I want to capture {{capture_what}} in under 10 seconds, so I can get back to what I was doing without losing the thought.',
          job_type: 'functional',
          importance: 5,
          satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Stay on top of {{domain}} without opening a laptop',
        description_template: 'When I am away from my desk, I want to check on {{domain}} status and take quick actions from my phone, so I can stay responsive without being tethered to a computer.',
        default_properties: {
          statement: 'When I am away from my desk, I want to check on {{domain}} status and act from my phone, so I can stay responsive without being tethered to a computer.',
          job_type: 'functional',
          importance: 4,
          satisfaction: 3,
        },
      },
      {
        type: 'need',
        title_template: 'Constant context-switching between apps kills flow',
        description_template: 'To complete a single task, the user has to jump between 3-4 apps. Each switch risks losing the original intent. Notifications from other apps add to the chaos.',
        default_properties: { frequency: 5, severity: 4 },
      },
      {
        type: 'need',
        title_template: 'Unreliable connectivity makes syncing unpredictable',
        description_template: 'On the commute or in buildings with poor signal, data fails to sync. The user does not trust that their input was saved, so they either wait for WiFi or avoid using the app entirely.',
        default_properties: { frequency: 4, severity: 3 },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 1, target_index: 3 },
      { source_index: 2, target_index: 4 },
    ],
    prompts: {
      persona_name: "What's this persona's name?",
      persona_role: 'Their role? (e.g. Busy Parent, Sales Rep on the Road, Fitness Enthusiast)',
      persona_context: 'Describe their world: lifestyle, work style, when/where they use their phone',
      persona_motivation: 'What drives them? Why would they reach for your app?',
      phone_usage: 'How much do they use their phone? (e.g. 3-4 hours, constantly, only for essentials)',
      primary_device: 'Primary device? (e.g. iPhone 15, Android mid-range, iPad mini)',
      capture_what: 'What do they need to capture quickly? (e.g. ideas, expenses, photos, tasks)',
      domain: 'What domain do they need to monitor? (e.g. team updates, fitness stats, order status)',
    },
  },
  {
    id: 'mobile-engagement-loop',
    name: 'App Engagement Loop',
    description: 'A mobile app funnel from download to daily habit: 5 stages covering onboarding, first value, habit formation, and sharing.',
    industries: ['mobile'],
    stages: ['mvp', 'growth'],
    entities: [
      {
        type: 'funnel',
        title_template: '{{app_name}} Engagement Loop',
        description_template: 'Mobile app engagement funnel for {{app_name}}. Tracks the user journey from app store download to habitual daily usage and organic sharing.',
        default_properties: {},
        default_tags: ['mobile', 'engagement-loop'],
      },
      {
        type: 'funnel_step',
        title_template: 'Download: Installs from app store',
        description_template: 'User discovers the app through {{discovery_channel}} and installs it. First impression: app store listing, screenshots, reviews, and download size all matter.',
        default_properties: { order: 1 },
        default_tags: ['download'],
      },
      {
        type: 'funnel_step',
        title_template: 'Onboard: Completes first-run experience',
        description_template: 'User opens the app for the first time. Goal: get them to {{onboarding_goal}} within 60 seconds. Minimize permission prompts, skip lengthy tutorials, show value immediately.',
        default_properties: { order: 2 },
        default_tags: ['onboarding'],
      },
      {
        type: 'funnel_step',
        title_template: 'First Value: Completes the core action',
        description_template: 'User experiences the primary value proposition by completing {{core_action}}. This is the "aha moment": the point where the app proves it is worth keeping.',
        default_properties: { order: 3 },
        default_tags: ['activation'],
      },
      {
        type: 'funnel_step',
        title_template: 'Habit: Returns daily/weekly without prompting',
        description_template: 'User returns to the app on their own, not because of a push notification, but because the app has become part of their routine. Trigger: {{habit_trigger}}.',
        default_properties: { order: 4 },
        default_tags: ['retention', 'habit'],
      },
      {
        type: 'funnel_step',
        title_template: 'Share: Invites others or creates shareable content',
        description_template: 'User shares their results, invites friends, or creates content that drives new downloads. Viral loop: shared content → app store → new user → shared content.',
        default_properties: { order: 5 },
        default_tags: ['referral', 'viral'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 0, target_index: 3 },
      { source_index: 0, target_index: 4 },
      { source_index: 0, target_index: 5 },
    ],
    prompts: {
      app_name: "What's your app called?",
      discovery_channel: 'Primary discovery channel? (e.g. App Store search, TikTok, word of mouth)',
      onboarding_goal: 'What should the user do within 60 seconds of opening? (e.g. create their first entry, see their dashboard, connect an account)',
      core_action: "What's the core action that delivers value? (e.g. complete a workout, log a meal, send a message)",
      habit_trigger: "What triggers them to open the app habitually? (e.g. morning routine, arriving at gym, feeling bored)",
    },
  },
  {
    id: 'mobile-launch-checklist',
    name: 'Mobile Launch Checklist',
    description: 'A release milestone with the 5 essential features every mobile app needs at launch: onboarding, core loop, notifications, analytics, and crash reporting.',
    industries: ['mobile'],
    stages: ['mvp'],
    entities: [
      {
        type: 'release',
        title_template: '{{app_name}} v1.0: App Store Launch',
        description_template: 'First public release of {{app_name}}. Target: {{launch_date}}. Minimum viable features to validate the core value proposition with real users.',
        default_properties: {},
        default_tags: ['launch', 'v1'],
      },
      {
        type: 'feature',
        title_template: 'Onboarding Flow',
        description_template: 'First-run experience that gets users to value in under 60 seconds. Includes: account creation (social auth), permission requests (only what is needed), and guided first action. No tutorial walls.',
        default_properties: { status: 'planned' },
        default_tags: ['onboarding', 'must-have'],
      },
      {
        type: 'feature',
        title_template: '{{core_loop_name}}',
        description_template: '{{core_loop_description}}. This is the reason the app exists: the core loop users come back for every day.',
        default_properties: { status: 'planned' },
        default_tags: ['core-loop', 'must-have'],
      },
      {
        type: 'feature',
        title_template: 'Push Notifications',
        description_template: 'Targeted push notifications to drive re-engagement. Day 1: welcome + first tip. Day 3: value reminder. Day 7: social proof. Opt-in prompt deferred until after first value moment.',
        default_properties: { status: 'planned' },
        default_tags: ['retention', 'notifications'],
      },
      {
        type: 'feature',
        title_template: 'Analytics & Event Tracking',
        description_template: 'Core event tracking: app_open, onboarding_complete, core_action_complete, session_duration, retention_d1/d7/d30. Tooling: {{analytics_tool}}. Privacy-first; no PII in events.',
        default_properties: { status: 'planned' },
        default_tags: ['analytics', 'infrastructure'],
      },
      {
        type: 'feature',
        title_template: 'Crash Reporting & Error Monitoring',
        description_template: 'Automated crash reporting with stack traces, device info, and reproduction steps. Tooling: {{crash_tool}}. Alert threshold: crash-free rate below 99.5%.',
        default_properties: { status: 'planned' },
        default_tags: ['stability', 'infrastructure'],
      },
    ],
    edges: [],
    prompts: {
      app_name: "What's your app called?",
      launch_date: 'Target launch date? (e.g. Q2 2026, May 2026)',
      core_loop_name: 'Name for the core loop feature? (e.g. Workout Tracker, Daily Journal, Photo Editor)',
      core_loop_description: 'What does the core loop do? Describe the primary user action.',
      analytics_tool: 'Analytics tool? (e.g. PostHog, Mixpanel, Amplitude)',
      crash_tool: 'Crash reporting tool? (e.g. Sentry, Crashlytics, Bugsnag)',
    },
  },
]
