import type { TemplateSet } from '../types.js'

export const ossTemplates: TemplateSet[] = [
  {
    id: 'oss-community-personas',
    name: 'OSS Community Personas',
    description: 'A contributor persona and a user persona with distinct jobs-to-be-done: the two audiences every open-source project must serve.',
    industries: ['oss'],
    stages: ['concept', 'validation'],
    entities: [
      {
        type: 'persona',
        title_template: '{{contributor_name}}, OSS Contributor',
        description_template: '{{contributor_motivation}}\n\nGoals: build public portfolio and credibility in the {{domain}} community, and solve a real problem they face in their own work.\n\nFrustrations: unclear contribution guidelines that make it hard to know where to start, and PRs that sit unreviewed for weeks, killing motivation.',
        default_properties: {
          context: '{{contributor_context}}. Contributes to open source {{contribution_frequency}}. Primarily works in {{primary_language}}.',
          is_primary: true,
          audience_role: 'partner',
        },
        default_tags: ['contributor', 'oss'],
      },
      {
        type: 'job',
        title_template: 'Contribute meaningfully to {{project_name}} without massive time investment',
        description_template: 'When I find a project I care about, I want to make a meaningful contribution in under 2 hours, so I can build my public profile and give back without derailing my day job.',
        default_properties: {
          statement: 'When I find a project I care about, I want to contribute meaningfully in under 2 hours, so I can build my profile and give back without derailing my day job.',
          job_type: 'functional',
          importance: 4,
          current_satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Learn {{domain}} best practices from real production code',
        description_template: 'When I want to level up my {{domain}} skills, I want to study and contribute to a well-maintained OSS project, so I can learn from real-world patterns instead of tutorials.',
        default_properties: {
          statement: 'When I want to level up, I want to study and contribute to a well-maintained OSS project, so I can learn from real-world patterns.',
          job_type: 'social',
          importance: 4,
          current_satisfaction: 3,
        },
      },
      {
        type: 'persona',
        title_template: '{{user_name}}, OSS User',
        description_template: '{{user_motivation}}\n\nGoals: solve {{core_problem}} without building from scratch or paying for a SaaS, and have confidence the project will be maintained long-term.\n\nFrustrations: documentation that is outdated or assumes expert knowledge, and breaking changes in minor versions with no migration guide.',
        default_properties: {
          context: '{{user_context}}. Evaluates OSS tools by: documentation quality, GitHub stars/activity, and "can I get this working in 15 minutes?"',
          audience_role: 'user',
        },
        default_tags: ['user', 'oss'],
      },
      {
        type: 'job',
        title_template: 'Get {{project_name}} working in my stack within 15 minutes',
        description_template: 'When I discover {{project_name}}, I want to install it and see it working in my project within 15 minutes, so I can evaluate whether it is worth adopting before investing more time.',
        default_properties: {
          statement: 'When I discover {{project_name}}, I want it working in my project within 15 minutes, so I can evaluate it before investing more time.',
          job_type: 'functional',
          importance: 5,
          current_satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Trust that {{project_name}} will not be abandoned',
        description_template: 'When I adopt an OSS dependency, I want to see active maintenance, a clear roadmap, and responsive issue handling, so I can trust it will not become abandonware that I have to fork or replace.',
        default_properties: {
          statement: 'When I adopt an OSS dependency, I want to see active maintenance and a clear roadmap, so I can trust it will not become abandonware.',
          job_type: 'emotional',
          importance: 5,
          current_satisfaction: 3,
        },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1, type: 'persona_pursues_job' },
      { source_index: 0, target_index: 2, type: 'persona_pursues_job' },
      { source_index: 3, target_index: 4, type: 'persona_pursues_job' },
      { source_index: 3, target_index: 5, type: 'persona_pursues_job' },
    ],
    prompts: {
      project_name: "What's your OSS project called?",
      domain: 'What domain? (e.g. developer tools, data pipelines, UI components)',
      contributor_name: 'Name for the contributor persona?',
      contributor_context: "Describe the contributor's background: what do they do, where do they work?",
      contributor_motivation: 'Why does this person contribute to open source?',
      contribution_frequency: 'How often? (e.g. weekends, a few hours/month, daily)',
      primary_language: 'Their primary programming language?',
      user_name: 'Name for the user persona?',
      user_context: "Describe the user's background: role, company, tech stack",
      user_motivation: 'Why would this person use your project?',
      core_problem: 'What problem does your project solve for users?',
    },
  },
  {
    id: 'oss-adoption-funnel',
    name: 'OSS Adoption Funnel',
    description: 'A 6-stage open-source adoption funnel from discovery to evangelism; tracks the journey from first GitHub star to active community champion.',
    industries: ['oss'],
    stages: ['validation', 'growth'],
    entities: [
      {
        type: 'funnel',
        title_template: '{{project_name}} Adoption Funnel',
        description_template: 'Open-source adoption funnel for {{project_name}}. Tracks the journey from discovery to active community evangelism.',
        default_properties: {},
        default_tags: ['oss', 'adoption'],
      },
      {
        type: 'funnel_step',
        title_template: 'Discover: Finds the project',
        description_template: 'Developer discovers {{project_name}} through: GitHub trending, a blog post, conference talk, search for "{{search_terms}}", or peer recommendation. First impression: README quality.',
        default_properties: { step_index: 0 },
        default_tags: ['discovery'],
      },
      {
        type: 'funnel_step',
        title_template: 'Star: Bookmarks for later',
        description_template: 'Developer stars the repo. This signals interest but not commitment. They may never come back. Conversion driver: compelling README with clear problem statement and demo.',
        default_properties: { step_index: 1 },
        default_tags: ['interest'],
      },
      {
        type: 'funnel_step',
        title_template: 'Install: Adds to a project',
        description_template: 'Developer runs `npm install {{project_name}}` (or equivalent). They are now evaluating. Conversion driver: one-line install, zero config to start, clear quickstart guide.',
        default_properties: { step_index: 2 },
        default_tags: ['trial'],
      },
      {
        type: 'funnel_step',
        title_template: 'Use: Integrates into production',
        description_template: 'Developer moves from experimentation to production use. They depend on {{project_name}} for real workloads. Conversion driver: stability, docs for edge cases, migration guides.',
        default_properties: { step_index: 3 },
        default_tags: ['adoption'],
      },
      {
        type: 'funnel_step',
        title_template: 'Contribute: Submits PRs or reports issues',
        description_template: 'User becomes contributor. Files issues, submits bug fixes, or adds features. Conversion driver: clear CONTRIBUTING.md, labeled "good first issues", fast PR reviews.',
        default_properties: { step_index: 4 },
        default_tags: ['contribution'],
      },
      {
        type: 'funnel_step',
        title_template: 'Evangelize: Actively promotes the project',
        description_template: 'Contributor becomes evangelist. Writes blog posts, gives talks, answers Stack Overflow questions, recommends to peers. Conversion driver: recognition, community belonging, shared mission.',
        default_properties: { step_index: 5 },
        default_tags: ['evangelism'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1, type: 'funnel_contains_funnel_step' },
      { source_index: 0, target_index: 2, type: 'funnel_contains_funnel_step' },
      { source_index: 0, target_index: 3, type: 'funnel_contains_funnel_step' },
      { source_index: 0, target_index: 4, type: 'funnel_contains_funnel_step' },
      { source_index: 0, target_index: 5, type: 'funnel_contains_funnel_step' },
      { source_index: 0, target_index: 6, type: 'funnel_contains_funnel_step' },
    ],
    prompts: {
      project_name: "What's your project called?",
      search_terms: 'What would someone Google to find this? (e.g. "react state management", "python data validation")',
    },
  },
  {
    id: 'oss-to-commercial',
    name: 'OSS to Commercial',
    description: 'The open-core business model: free community value proposition, paid enterprise value proposition, and the revenue stream that bridges them.',
    industries: ['oss'],
    stages: ['growth', 'mature'],
    entities: [
      {
        type: 'business_model',
        title_template: '{{project_name}} Open-Core Model',
        description_template: 'Open-core business model: {{project_name}} is free and MIT-licensed. The commercial offering adds {{commercial_value}} for teams that need it. Community drives adoption; enterprise drives revenue. Customer segments: individual developers (free), engineering teams (paid), and enterprise (custom). Channels: GitHub / open-source discovery, developer content marketing, and bottom-up adoption within companies. Key activities: maintain the OSS project, build enterprise features, developer relations, and community support. Key resources: the core team, community contributors, documentation, and cloud infrastructure.',
        default_properties: {
          pattern: 'hybrid',
          status: 'drafted',
        },
        default_tags: ['open-core', 'oss-commercial'],
      },
      {
        type: 'value_proposition',
        title_template: 'Community: {{project_name}} is free, open, and yours',
        description_template: 'For individual developers who {{community_need}}, {{project_name}} is the open-source {{category}} that {{community_benefit}}. Free forever, MIT licensed, no vendor lock-in. Gains: solve {{core_problem}} without paying, full source code to fork/modify/extend, and an active community for support. Pain relievers: no vendor lock-in, no usage limits, and no surprise pricing changes.',
        default_properties: {
          offering_type: 'product',
          validation_state: 'validated',
          status: 'validated',
        },
        default_tags: ['community', 'free-tier'],
      },
      {
        type: 'value_proposition',
        title_template: 'Enterprise: {{project_name}} Cloud, {{commercial_value}}',
        description_template: 'For engineering teams that have adopted {{project_name}} and need {{commercial_value}}, the commercial offering adds what the OSS version cannot: SLAs, SSO, audit logs, and dedicated support. Gains: {{commercial_value}}, SLA-backed uptime guarantees, and dedicated support with SLAs. Pain relievers: no self-hosting burden, compliance-ready (SOC2, SSO, audit logs), and a zero-rewrite migration path from OSS.',
        default_properties: {
          offering_type: 'service',
          validation_state: 'hypothesis',
          status: 'untested',
        },
        default_tags: ['enterprise', 'paid-tier'],
      },
      {
        type: 'revenue_stream',
        title_template: '{{project_name}} Cloud Subscriptions',
        description_template: 'Self-serve cloud subscriptions starting at {{starter_price}}/month for small teams. Enterprise tier with custom pricing for >50 seats. Target: {{revenue_target}} ARR within {{revenue_timeline}}.',
        default_properties: { stream_type: 'subscription' },
        default_tags: ['subscription', 'cloud', 'primary'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1, type: 'business_model_delivers_value_proposition' },
      { source_index: 0, target_index: 2, type: 'business_model_delivers_value_proposition' },
      { source_index: 0, target_index: 3, type: 'business_model_earns_via_revenue_stream' },
    ],
    prompts: {
      project_name: "What's your project called?",
      category: 'What category? (e.g. database, CLI tool, UI framework)',
      core_problem: 'What problem does it solve?',
      community_need: 'What do community users need? (e.g. manage state in React apps, validate data pipelines)',
      community_benefit: 'Core benefit for free users? (e.g. reduces boilerplate by 80%, catches bugs before production)',
      commercial_value: 'What does the paid version add? (e.g. team collaboration, hosted cloud, enterprise SSO)',
      starter_price: 'Starting price for small teams? (e.g. $29, $49)',
      revenue_target: 'ARR target? (e.g. $100K, $500K, $1M)',
      revenue_timeline: 'Timeline for that target? (e.g. 12 months, 18 months)',
    },
  },
]
