import type { TemplateSet } from '../types.js'

export const saasTemplates: TemplateSet[] = [
  {
    id: 'saas-technical-buyer-persona',
    name: 'SaaS Technical Buyer Persona',
    description: 'A technical decision-maker persona with 2 jobs-to-be-done and 2 pain points: the foundation for any B2B SaaS product.',
    industries: ['saas'],
    stages: ['idea', 'mvp'],
    entities: [
      {
        type: 'persona',
        title_template: '{{persona_name}}, {{persona_role}}',
        description_template: '{{persona_motivation}}',
        default_properties: {
          context: '{{persona_context}}',
          goals: ['Reduce time spent on {{problem_domain}} by 50%', 'Ship faster without sacrificing quality'],
          frustrations: ['Current tools require too much manual work', 'Context-switching between disconnected tools kills focus'],
        },
        default_tags: ['technical-buyer', 'b2b'],
      },
      {
        type: 'job',
        title_template: 'Evaluate and adopt new {{problem_domain}} tools',
        description_template: 'When I find my team spending too much time on {{problem_domain}}, I want to evaluate and adopt better tooling, so I can reclaim engineering hours for high-value work.',
        default_properties: {
          statement: 'When I find my team spending too much time on {{problem_domain}}, I want to evaluate and adopt better tooling, so I can reclaim engineering hours for high-value work.',
          job_type: 'functional',
          importance: 5,
          satisfaction: 2,
        },
      },
      {
        type: 'job',
        title_template: 'Prove ROI of tooling decisions to leadership',
        description_template: 'When I choose a new tool for my team, I want to demonstrate measurable ROI within 90 days, so I can justify the investment and build credibility for future decisions.',
        default_properties: {
          statement: 'When I choose a new tool for my team, I want to demonstrate measurable ROI within 90 days, so I can justify the investment and build credibility for future decisions.',
          job_type: 'social',
          importance: 4,
          satisfaction: 2,
        },
      },
      {
        type: 'need',
        title_template: 'Manual {{problem_domain}} workflows eat 10+ hours/week',
        description_template: 'The team spends over 10 hours per week on repetitive {{problem_domain}} tasks that should be automated. This is the #1 time sink.',
        default_properties: { frequency: 5, severity: 4 },
      },
      {
        type: 'need',
        title_template: 'No single source of truth: data scattered across tools',
        description_template: 'Critical {{problem_domain}} data lives in 3-5 different tools. Nobody trusts any single source, so decisions get delayed or made on gut feel.',
        default_properties: { frequency: 4, severity: 4 },
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 1, target_index: 3 },
      { source_index: 1, target_index: 4 },
    ],
    prompts: {
      persona_name: "What's this persona's name? (e.g. Alex Chen, Jordan Rivera)",
      persona_role: "What's their role? (e.g. VP of Engineering, Staff Developer)",
      persona_context: 'Describe their world: company size, industry, team, daily reality',
      persona_motivation: 'What drives this person? What gets them excited about their work?',
      problem_domain: 'What problem domain does your product address? (e.g. deployment, data pipelines, customer support)',
    },
  },
  {
    id: 'saas-plg-funnel',
    name: 'PLG Acquisition Funnel',
    description: 'A product-led growth funnel with 5 stages from awareness to referral: the pirate metrics (AARRR) framework applied to your product.',
    industries: ['saas'],
    stages: ['mvp', 'growth'],
    entities: [
      {
        type: 'funnel',
        title_template: '{{product_name}} PLG Funnel',
        description_template: 'Product-led growth acquisition funnel for {{product_name}}. Tracks the full user journey from first touch to active referral.',
        default_properties: {},
        default_tags: ['plg', 'aarrr'],
      },
      {
        type: 'funnel_step',
        title_template: 'Awareness: First discovers {{product_name}}',
        description_template: 'User first hears about or encounters the product. Channels: organic search, content marketing, word of mouth, social.',
        default_properties: { order: 1 },
        default_tags: ['awareness'],
      },
      {
        type: 'funnel_step',
        title_template: 'Activation: Reaches first value moment',
        description_template: 'User signs up and experiences the core value proposition for the first time. The "aha moment": when they understand why this exists.',
        default_properties: { order: 2 },
        default_tags: ['activation'],
      },
      {
        type: 'funnel_step',
        title_template: 'Revenue: Converts to paid',
        description_template: 'User upgrades from free to paid. Triggered by hitting usage limits, needing team features, or wanting advanced capabilities.',
        default_properties: { order: 3 },
        default_tags: ['revenue'],
      },
      {
        type: 'funnel_step',
        title_template: 'Retention: Returns and builds habits',
        description_template: 'User comes back repeatedly and integrates the product into their workflow. Daily/weekly active usage becomes habitual.',
        default_properties: { order: 4 },
        default_tags: ['retention'],
      },
      {
        type: 'funnel_step',
        title_template: 'Referral: Tells others and invites teammates',
        description_template: 'User actively recommends the product to peers, invites teammates, or shares publicly. The viral coefficient that compounds growth.',
        default_properties: { order: 5 },
        default_tags: ['referral'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 0, target_index: 3 },
      { source_index: 0, target_index: 4 },
      { source_index: 0, target_index: 5 },
    ],
    prompts: {
      product_name: "What's your product called?",
    },
  },
  {
    id: 'saas-business-model',
    name: 'SaaS Business Model',
    description: 'A complete SaaS business model with revenue stream, value proposition, and cost structure: the economics of your product in one template.',
    industries: ['saas'],
    stages: ['mvp', 'growth'],
    entities: [
      {
        type: 'business_model',
        title_template: '{{product_name}} SaaS Model',
        description_template: 'Subscription-based SaaS business model for {{product_name}}. Recurring revenue with tiered pricing.',
        default_properties: {
          canvas_type: 'lean',
          key_activities: ['Product development', 'Customer onboarding', 'Support & success'],
          key_resources: ['Engineering team', 'Cloud infrastructure', 'Customer data'],
          status: 'draft',
        },
        default_tags: ['saas', 'subscription'],
      },
      {
        type: 'revenue_stream',
        title_template: 'Subscription Revenue: {{pricing_model}}',
        description_template: 'Primary revenue from {{pricing_model}} subscriptions. Target ARPU: {{target_arpu}}/month.',
        default_properties: {},
        default_tags: ['recurring', 'primary'],
      },
      {
        type: 'value_proposition',
        title_template: '{{product_name}} saves {{persona_type}} {{time_saved}}',
        description_template: 'For {{persona_type}} who {{core_pain}}, {{product_name}} is the {{category}} that {{key_benefit}}. Unlike {{alternative}}, we {{differentiator}}.',
        default_properties: { status: 'draft' },
      },
      {
        type: 'cost_structure',
        title_template: '{{product_name}} Operating Costs',
        description_template: 'Key cost drivers: infrastructure (cloud hosting, APIs), people (engineering, support), and acquisition (marketing, sales tooling).',
        default_properties: {},
        default_tags: ['opex'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 1 },
      { source_index: 0, target_index: 2 },
      { source_index: 0, target_index: 3 },
    ],
    prompts: {
      product_name: "What's your product called?",
      pricing_model: 'What pricing model? (e.g. per-seat, usage-based, flat-rate, tiered)',
      target_arpu: 'What monthly ARPU are you targeting? (e.g. $49, $199)',
      persona_type: 'Who is the primary buyer? (e.g. engineering managers, solo founders)',
      core_pain: "What's the main pain your product solves?",
      category: 'What category is your product? (e.g. workflow automation tool, analytics platform)',
      key_benefit: 'What is the single biggest benefit?',
      alternative: 'What do people use today instead? (e.g. spreadsheets, Jira, manual processes)',
      differentiator: 'What makes you fundamentally different from that alternative?',
      time_saved: 'How much time/effort does this save? (e.g. 10 hours/week, 3x faster)',
    },
  },
  {
    id: 'saas-feature-roadmap',
    name: 'Feature-Led Roadmap',
    description: '3 features grouped into 3 epics with a release milestone: a structured starting point for your first product roadmap.',
    industries: ['saas'],
    stages: ['mvp', 'growth'],
    entities: [
      {
        type: 'release',
        title_template: '{{release_name}}',
        description_template: 'Target: {{release_date}}. The milestone that delivers {{release_goal}} to users.',
        default_properties: {},
        default_tags: ['milestone'],
      },
      {
        type: 'feature',
        title_template: '{{feature_1_name}}',
        description_template: '{{feature_1_description}}',
        default_properties: { status: 'planned' },
      },
      {
        type: 'feature',
        title_template: '{{feature_2_name}}',
        description_template: '{{feature_2_description}}',
        default_properties: { status: 'planned' },
      },
      {
        type: 'feature',
        title_template: '{{feature_3_name}}',
        description_template: '{{feature_3_description}}',
        default_properties: { status: 'planned' },
      },
      {
        type: 'epic',
        title_template: '{{epic_1_name}}',
        description_template: 'Epic grouping the core functionality for {{feature_1_name}}.',
        default_properties: {},
      },
      {
        type: 'epic',
        title_template: '{{epic_2_name}}',
        description_template: 'Epic grouping the core functionality for {{feature_2_name}}.',
        default_properties: {},
      },
      {
        type: 'epic',
        title_template: '{{epic_3_name}}',
        description_template: 'Epic grouping the core functionality for {{feature_3_name}}.',
        default_properties: {},
      },
    ],
    edges: [
      { source_index: 1, target_index: 4 },
      { source_index: 2, target_index: 5 },
      { source_index: 3, target_index: 6 },
    ],
    prompts: {
      release_name: "What's this release called? (e.g. v1.0, Public Beta, MVP Launch)",
      release_date: 'Target date? (e.g. Q2 2026, June 2026)',
      release_goal: 'What does this release achieve for users?',
      feature_1_name: 'Feature 1: the must-have. What is it?',
      feature_1_description: 'Describe what Feature 1 does for the user.',
      feature_2_name: 'Feature 2: the differentiator. What sets you apart?',
      feature_2_description: 'Describe what Feature 2 does for the user.',
      feature_3_name: 'Feature 3: the delight. What makes users love this?',
      feature_3_description: 'Describe what Feature 3 does for the user.',
      epic_1_name: 'Epic name for Feature 1 work (e.g. Core Engine, Auth & Onboarding)',
      epic_2_name: 'Epic name for Feature 2 work',
      epic_3_name: 'Epic name for Feature 3 work',
    },
  },
  {
    id: 'saas-hypothesis-set',
    name: 'SaaS Hypothesis Set',
    description: '3 structured hypotheses (value, usability, and feasibility) plus an experiment template. Start validating before you build.',
    industries: ['saas'],
    stages: ['idea', 'mvp'],
    entities: [
      {
        type: 'hypothesis',
        title_template: 'Value: {{persona_type}} will pay for {{core_capability}}',
        description_template: 'We believe {{persona_type}} will pay ${{price_point}}/mo for {{core_capability}} because {{value_reason}}.',
        default_properties: {
          we_believe: '{{persona_type}} will pay for {{core_capability}}',
          will_result_in: 'At least {{conversion_target}}% of trial users converting to paid within 14 days',
          we_know_when: 'Trial-to-paid conversion rate exceeds {{conversion_target}}%',
          status: 'untested',
        },
        default_tags: ['value-hypothesis'],
      },
      {
        type: 'hypothesis',
        title_template: 'Usability: New users reach value in under {{activation_time}}',
        description_template: 'We believe new users can complete the core workflow without help within {{activation_time}} of signing up.',
        default_properties: {
          we_believe: 'New users can complete the core workflow independently',
          will_result_in: '{{activation_target}}% of signups completing the first value action within {{activation_time}}',
          we_know_when: 'Activation rate exceeds {{activation_target}}% within {{activation_time}}',
          status: 'untested',
        },
        default_tags: ['usability-hypothesis'],
      },
      {
        type: 'hypothesis',
        title_template: 'Feasibility: {{core_capability}} can run at {{scale_target}} scale',
        description_template: 'We believe the technical architecture can support {{scale_target}} without degrading performance below acceptable thresholds.',
        default_properties: {
          we_believe: 'The architecture supports {{scale_target}} scale',
          will_result_in: 'P95 latency under {{latency_target}}ms at {{scale_target}} load',
          we_know_when: 'Load test confirms P95 < {{latency_target}}ms',
          status: 'untested',
        },
        default_tags: ['feasibility-hypothesis'],
      },
      {
        type: 'experiment',
        title_template: 'Validate: {{experiment_name}}',
        description_template: 'Test the riskiest hypothesis first. Method: {{experiment_method}}. Duration: {{experiment_duration}}.',
        default_properties: {
          method: '{{experiment_method}}',
          status: 'planned',
        },
        default_tags: ['validation'],
      },
    ],
    edges: [
      { source_index: 0, target_index: 3 },
    ],
    prompts: {
      persona_type: 'Who is the target user? (e.g. engineering managers, solo founders)',
      core_capability: "What's the core capability you're betting on?",
      price_point: 'What price point are you considering? (just the number)',
      value_reason: 'Why would they pay for this? What makes it worth it?',
      conversion_target: 'What trial-to-paid conversion rate would validate demand? (e.g. 5, 10)',
      activation_time: 'How quickly should new users reach value? (e.g. 5 minutes, 1 hour)',
      activation_target: 'What % of signups completing the first action validates usability? (e.g. 60, 80)',
      scale_target: 'What scale does the product need to support? (e.g. 10K concurrent users, 1M API calls/day)',
      latency_target: 'Acceptable P95 latency in ms? (e.g. 200, 500)',
      experiment_name: 'Name for your first experiment (e.g. Landing Page Smoke Test, Concierge MVP)',
      experiment_method: 'How will you test this? (e.g. landing page with waitlist, 5 user interviews, prototype test)',
      experiment_duration: 'How long will the experiment run? (e.g. 2 weeks, 1 sprint)',
    },
  },
]
